### ISSUE TITLE
Decoupling mobile-ui

### ISSUE THREAD

**Issue by ech0s7r** [bufferapp/clean-architecture-components-boilerplate#16]
https://github.com/bufferapp/clean-architecture-components-boilerplate/blob/15838f22b1acea74fbfbdb7612e8ed3cc38b3abc/mobile-ui/build.gradle#L67

The module _mobile-ui_ should depend only on the module _presentation_ and not on all the modules.

**Comment by hitherejoe** [comment]
You would need to abstract out the dependency injection logic for this - which IMO would be overcomplicating things. This would be a per project decision
