### ISSUE TITLE
Android Studio 3.2 Canary 14 Doesn't find any tests

### ISSUE THREAD

**Issue by dmfrey** [bufferapp/clean-architecture-components-boilerplate#19]
Import the project into the latest canary for 3.2. You have to update a few dependencies like the android plugin and references to `compile` in the gradle files.  `compile` needs to be changed to `implementation`.

Once it's complete, go into any subproject and try to run the tests by right-click the root package and select Run Tests in `...`.  You will see the output below:

```
0 test classes found in package '<default package>'

Process finished with exit code 254
Empty test suite.
```

**Comment by dmfrey** [comment]
You appear to be able to run individual tests.

It really seems like the folders aren't demarcated as Source and Test Source. Maybe its missing a facet or something, but importing as a gradle project doesn't resolve it.

**Comment by dmfrey** [comment]
This doesn't appear to be the case in Android Studio 3.1.2. I was thinking this was an Android Studio/Gradle integration issue, but it is probably just an issue with the canary build of Android Studio

**Comment by daniellAlgar** [comment]
Still an issue in AS 3.2 Beta 5.

**Comment by hitherejoe** [comment]
this is an AS issue, not related to this project :)
