### ISSUE TITLE
BrowseBufferoosViewModel doesn't survive configuration change

### ISSUE THREAD

**Issue by vlazzle** [bufferapp/clean-architecture-components-boilerplate#3]
Steps to repro:

1. Set a breakpoint or log in BrowseBufferoosViewModel.init
2. Build & deploy
3. Rotate device
4. Observe that the log or breakpoint in BrowseBufferoosViewModel.init is hit for every rotation

[`android.arch.lifecycle.ViewModel`s are meant to survive config changes](https://developer.android.com/topic/libraries/architecture/viewmodel.html). 

BrowseBufferoosViewModel will survive config changes if it's retrieved in BrowseActivity the normal way using `ViewModelProviders.of`. If you prefer to inject with dagger, take a look at [this sample](https://github.com/satorufujiwara/kotlin-architecture-components#multibinding), then retrieve the ViewModel [like so](https://github.com/satorufujiwara/kotlin-architecture-components/blob/master/app/src/main/java/jp/satorufujiwara/kotlin/ui/main/MainFragment.kt#L28)

**Comment by hitherejoe** [comment]
Awesome spot, thanks! Now injecting a Factory for the ViewModel (https://github.com/bufferapp/clean-architecture-components-boilerplate/blob/master/presentation/src/main/java/org/buffer/android/boilerplate/presentation/browse/BrowseBufferoosViewModelFactory.kt) and then using this when fetching the ViewModel from the provider (https://github.com/bufferapp/clean-architecture-components-boilerplate/blob/master/mobile-ui/src/main/java/org/buffer/android/boilerplate/ui/browse/BrowseActivity.kt#L34)

Thanks again!

**Comment by vlazzle** [comment]
Great! You're very welcome
